// import 'package:flutter/material.dart';

// final ThemeData myTheme = ThemeData(
//   primarySwatch: MaterialColor(4285881268, {
//     50: Color(0xfff0eef7),
//     100: Color(0xffe2dcef),
//     200: Color(0xffc4b9df),
//     300: Color(0xffa796cf),
//     400: Color(0xff8973bf),
//     500: Color(0xff6c50af),
//     600: Color(0xff56408c),
//     700: Color(0xff413069),
//     800: Color(0xff2b2046),
//     900: Color(0xff161023)
//   }),
//   brightness: Brightness.light,
//   primaryColor: Color(0xff755bb4),
//   primaryColorLight: Color(0xffe2dcef),
//   primaryColorDark: Color(0xff413069),
//   canvasColor: Color(0xfffafafa),
//   scaffoldBackgroundColor: Color(0xfffafafa),
//   bottomAppBarColor: Color(0xffffffff),
//   cardColor: Color(0xffffffff),
//   dividerColor: Color(0x1f000000),
//   highlightColor: Color(0x66bcbcbc),
//   splashColor: Color(0x66c8c8c8),
//   selectedRowColor: Color(0xfff5f5f5),
//   unselectedWidgetColor: Color(0x8a000000),
//   disabledColor: Color(0x61000000),
//   toggleableActiveColor: Color(0xff56408c),
//   secondaryHeaderColor: Color(0xfff0eef7),
//   backgroundColor: Color(0xffc4b9df),
//   dialogBackgroundColor: Color(0xffffffff),
//   indicatorColor: Color(0xff6c50af),
//   hintColor: Color(0x8a000000),
//   errorColor: Color(0xffd32f2f),
//   buttonTheme: ButtonThemeData(
//     textTheme: ButtonTextTheme.normal,
//     minWidth: 88,
//     height: 36,
//     padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
//     shape: RoundedRectangleBorder(
//       side: BorderSide(
//         color: Color(0xff000000),
//         width: 0,
//         style: BorderStyle.none,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(2.0)),
//     ),
//     alignedDropdown: false,
//     buttonColor: Color(0xffe0e0e0),
//     disabledColor: Color(0x61000000),
//     highlightColor: Color(0x29000000),
//     splashColor: Color(0x1f000000),
//     focusColor: Color(0x1f000000),
//     hoverColor: Color(0x0a000000),
//     colorScheme: ColorScheme(
//       primary: Color(0xff755bb4),
//       secondary: Color(0xff6c50af),
//       surface: Color(0xffffffff),
//       background: Color(0xffc4b9df),
//       error: Color(0xffd32f2f),
//       onPrimary: Color(0xffffffff),
//       onSecondary: Color(0xffffffff),
//       onSurface: Color(0xff000000),
//       onBackground: Color(0xffffffff),
//       onError: Color(0xffffffff),
//       brightness: Brightness.light,
//     ),
//   ),
//   textTheme: TextTheme(
//     caption: TextStyle(
//       color: Color(0x8a000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     button: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     overline: TextStyle(
//       color: Color(0xff000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//   ),
//   primaryTextTheme: TextTheme(
//     caption: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     button: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     subtitle: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     overline: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//   ),
//   accentTextTheme: TextTheme(
//     display4: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     display3: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     display2: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     display1: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     headline: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     title: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     subhead: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     body2: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     body1: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     caption: TextStyle(
//       color: Color(0xb3ffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     button: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     subtitle: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     overline: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//   ),
//   inputDecorationTheme: InputDecorationTheme(
//     labelStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     helperStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     hintStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     errorStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     errorMaxLines: null,
//     hasFloatingPlaceholder: true,
//     isDense: false,
//     contentPadding: EdgeInsets.only(top: 12, bottom: 12, left: 0, right: 0),
//     isCollapsed: false,
//     prefixStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     suffixStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     counterStyle: TextStyle(
//       color: Color(0xdd000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     filled: false,
//     fillColor: Color(0x00000000),
//     errorBorder: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//     focusedBorder: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//     focusedErrorBorder: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//     disabledBorder: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//     enabledBorder: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//     border: UnderlineInputBorder(
//       borderSide: BorderSide(
//         color: Color(0xff000000),
//         width: 1,
//         style: BorderStyle.solid,
//       ),
//       borderRadius: BorderRadius.all(Radius.circular(4.0)),
//     ),
//   ),
//   iconTheme: IconThemeData(
//     color: Color(0xdd000000),
//     opacity: 1,
//     size: 24,
//   ),
//   primaryIconTheme: IconThemeData(
//     color: Color(0xffffffff),
//     opacity: 1,
//     size: 24,
//   ),
//   accentIconTheme: IconThemeData(
//     color: Color(0xffffffff),
//     opacity: 1,
//     size: 24,
//   ),
//   sliderTheme: SliderThemeData(
//     activeTrackColor: null,
//     inactiveTrackColor: null,
//     disabledActiveTrackColor: null,
//     disabledInactiveTrackColor: null,
//     activeTickMarkColor: null,
//     inactiveTickMarkColor: null,
//     disabledActiveTickMarkColor: null,
//     disabledInactiveTickMarkColor: null,
//     thumbColor: null,
//     disabledThumbColor: null,
//     thumbShape: null(),
//     overlayColor: null,
//     valueIndicatorColor: null,
//     valueIndicatorShape: null(),
//     showValueIndicator: null,
//     valueIndicatorTextStyle: TextStyle(
//       color: Color(0xffffffff),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//   ),
//   tabBarTheme: TabBarTheme(
//     indicatorSize: TabBarIndicatorSize.tab,
//     labelColor: Color(0xffffffff),
//     unselectedLabelColor: Color(0xb2ffffff),
//   ),
//   chipTheme: ChipThemeData(
//     backgroundColor: Color(0x1f000000),
//     brightness: Brightness.light,
//     deleteIconColor: Color(0xde000000),
//     disabledColor: Color(0x0c000000),
//     labelPadding: EdgeInsets.only(top: 0, bottom: 0, left: 8, right: 8),
//     labelStyle: TextStyle(
//       color: Color(0xde000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     padding: EdgeInsets.only(top: 4, bottom: 4, left: 4, right: 4),
//     secondaryLabelStyle: TextStyle(
//       color: Color(0x3d000000),
//       fontSize: null,
//       fontWeight: FontWeight.w400,
//       fontStyle: FontStyle.normal,
//     ),
//     secondarySelectedColor: Color(0x3d755bb4),
//     selectedColor: Color(0x3d000000),
//     shape: StadiumBorder(
//         side: BorderSide(
//       color: Color(0xff000000),
//       width: 0,
//       style: BorderStyle.none,
//     )),
//   ),
//   dialogTheme: DialogTheme(
//       shape: RoundedRectangleBorder(
//     side: BorderSide(
//       color: Color(0xff000000),
//       width: 0,
//       style: BorderStyle.none,
//     ),
//     borderRadius: BorderRadius.all(Radius.circular(0.0)),
//   )),
// );
